### ISSUE TITLE
Where the Release directory?

### ISSUE THREAD

**Issue by LucasLuth** [SpintroniK/eXaDrums#1]
The git was updated today, but the Release directory was removed. Same in the libeXaDrums, but there more direcotories was removed.

**Comment by SpintroniK** [comment]
The new build system is autotools. 
The Eclipse makefiles that were in the Debug and Release folders have been replaced by configure.ac and Makefile.am.
The Readme will be updated shortly and describe how to build the binaries.
If you want to build exadrums, make sure you have autotools installed: `apt install autoconf automake libtool.`
Then you can do the following (edited): 
```
cd eXaDrums
mkdir build
autoreconf -fi
./configure --prefix=$(pwd)/build
make -j4 
sudo make install
```
This will install the binaries in the build folder.

**Comment by SpintroniK** [comment]
An answer has been provided, so I'm closing this issue.
