### ISSUE TITLE
Is it compatible with triggers pads? 

### ISSUE THREAD

**Issue by nicolasFernandez** [SpintroniK/eXaDrums#2]
I found your project amazing, and I was wondering if it would be compatible with one of this: http://my.roland.com/products/bt-1/

Thanks in advance

**Comment by SpintroniK** [comment]
It most likely is compatible.
All the Roland pad that I tested worked.
It depends on the board you use to connect your pad to the module.
I recommend you use the board described here: https://hackaday.io/project/9350-exadrums/log/153268-exadrums-a-drum-module-you-can-make 
And if it doesn't work as well as you excepted, you can still configure your trigger on the software side, here's how: https://hackaday.io/project/9350-exadrums/log/55157-configure-your-triggers
